-- 계정 TSPADM
-- 큐브원 테이블 입니다. 시작전 연락 주세요. [TSS 이준영M 02-6323-9859]
-- TS_INSU_ACDNT 테이블은  롤백 할 수도 있습니다.
ALTER TABLE TS_INSU_ACDNT ADD( PAY_TYPE VARCHAR2 (20 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( ZIP_CODE VARCHAR2 (20 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( DELV_SIDO VARCHAR2 (100 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( DELV_GUGUN VARCHAR2 (100 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( DELV_DONG VARCHAR2 (400 BYTE) );		
ALTER TABLE TS_INSU_ACDNT ADD( DELV_NM VARCHAR2 (50 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( DELV_TEL VARCHAR2 (50 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( DELV_MEMO VARCHAR2 (200 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( USIM_YN VARCHAR2 (10 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( TYP_PRE_SEND VARCHAR2 (10 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( SUB_PHONE_TYPE VARCHAR2 (10 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( PAY_TERMS VARCHAR2 (10 BYTE) );	
ALTER TABLE TS_INSU_ACDNT ADD( IDENT_TYPE VARCHAR2 (10 BYTE) );	
ALTER TABLE TS_INSU_ACDNT ADD( IDENT_NO VARCHAR2 (50 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( IDENT_DT VARCHAR2 (50 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( AGREE_DT VARCHAR2 (50 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( DELV_ADDR1 VARCHAR2 (400 BYTE) );
ALTER TABLE TS_INSU_ACDNT ADD( DELV_ADDR2 VARCHAR2 (400 BYTE) );

COMMENT ON COLUMN TS_INSU_ACDNT.PAY_TYPE IS '지불방법';
COMMENT ON COLUMN TS_INSU_ACDNT.ZIP_CODE IS '택배 수신 주소의 우편번호';
COMMENT ON COLUMN TS_INSU_ACDNT.DELV_SIDO IS '택배 수신 주소의 시도';
COMMENT ON COLUMN TS_INSU_ACDNT.DELV_GUGUN IS '택배 수신 주소의 구군';
COMMENT ON COLUMN TS_INSU_ACDNT.DELV_DONG IS '택배 수신 주소의 상세주소';
COMMENT ON COLUMN TS_INSU_ACDNT.DELV_NM IS '택배 수신자 이름';
COMMENT ON COLUMN TS_INSU_ACDNT.DELV_TEL IS '택배 수신자 연락번호';
COMMENT ON COLUMN TS_INSU_ACDNT.DELV_MEMO IS '배송시 요청 사항';
COMMENT ON COLUMN TS_INSU_ACDNT.USIM_YN IS '유심 구매 여부 [1: USIM 구매, 2: USIM 비구매';
COMMENT ON COLUMN TS_INSU_ACDNT.TYP_PRE_SEND IS '개통희망 여부 [1: 선개통, 2: 후개통]';
COMMENT ON COLUMN TS_INSU_ACDNT.SUB_PHONE_TYPE IS '대체폰 사용 유형  [1: 임대폰, 2: USIM 기변폰, 3: 착신전환, 4: 대체폰 사용 안함]';
COMMENT ON COLUMN TS_INSU_ACDNT.PAY_TERMS IS '요금 분할 납부 개월수';
COMMENT ON COLUMN TS_INSU_ACDNT.IDENT_TYPE IS '신분증 종류 [1: 주민등록증, 2:운전면허증, 3:외국인등록증]';
COMMENT ON COLUMN TS_INSU_ACDNT.IDENT_NO IS '신분증 번호 [주민등록증: 무입력, 운전면허증: 면허번호, 외국인등록증: 뒷 7자리입력]';
COMMENT ON COLUMN TS_INSU_ACDNT.IDENT_DT IS '신분증 발급일자 [주민등록증: 발급일자(YYYYMMDD), 운전면허증: 발급일자(YYYYMMDD), 외국인등록증: 발급일자(YYYYMMDD)]';
COMMENT ON COLUMN TS_INSU_ACDNT.AGREE_DT IS '개인정보 수집 동의 수신일시 [개인정보 수집 동의 수신일시(YYYYMMDDHH24MISS)]';
COMMENT ON COLUMN TS_INSU_ACDNT.DELV_ADDR1 IS '택배 수신 주소의 상세주소1';		
COMMENT ON COLUMN TS_INSU_ACDNT.DELV_ADDR2 IS '택배 수신 주소의 상세주소2';	
   
ALTER TABLE TS_CUST_INFO ADD( EMAIL VARCHAR2 (100 BYTE) );
ALTER TABLE TS_CUST_INFO ADD( EXP_DT VARCHAR2 (50 BYTE) );
ALTER TABLE TS_CUST_INFO ADD( CUST_TYP_CD VARCHAR2 (10 BYTE) );

COMMENT ON COLUMN TS_CUST_INFO.EMAIL IS '이메일';
COMMENT ON COLUMN TS_CUST_INFO.EXP_DT IS '단말 보험 만료일자';
COMMENT ON COLUMN TS_CUST_INFO.CUST_TYP_CD IS '개인/법인 구분';

ALTER TABLE TS_CUST_INFO_H ADD( EMAIL VARCHAR2 (100 BYTE) );
ALTER TABLE TS_CUST_INFO_H ADD( EXP_DT VARCHAR2 (50 BYTE) );
ALTER TABLE TS_CUST_INFO_H ADD( CUST_TYP_CD VARCHAR2 (10 BYTE) );

COMMENT ON COLUMN TS_CUST_INFO_H.EMAIL IS '이메일';
COMMENT ON COLUMN TS_CUST_INFO_H.EXP_DT IS '단말 보험 만료일자';
COMMENT ON COLUMN TS_CUST_INFO_H.CUST_TYP_CD IS '개인/법인 구분';

ALTER TABLE DEL_TS_CUST_INFO ADD( EMAIL VARCHAR2 (100 BYTE) );
ALTER TABLE DEL_TS_CUST_INFO ADD( EXP_DT VARCHAR2 (50 BYTE) );
ALTER TABLE DEL_TS_CUST_INFO ADD( CUST_TYP_CD VARCHAR2 (10 BYTE) );

COMMENT ON COLUMN DEL_TS_CUST_INFO.EMAIL IS '이메일';
COMMENT ON COLUMN DEL_TS_CUST_INFO.EXP_DT IS '단말 보험 만료일자';
COMMENT ON COLUMN DEL_TS_CUST_INFO.CUST_TYP_CD IS '개인/법인 구분';

ALTER TABLE DEL_TS_CUST_INFO_H ADD( EMAIL VARCHAR2 (100 BYTE) );
ALTER TABLE DEL_TS_CUST_INFO_H ADD( EXP_DT VARCHAR2 (50 BYTE) );
ALTER TABLE DEL_TS_CUST_INFO_H ADD( CUST_TYP_CD VARCHAR2 (10 BYTE) );

COMMENT ON COLUMN DEL_TS_CUST_INFO_H.EMAIL IS '이메일';
COMMENT ON COLUMN DEL_TS_CUST_INFO_H.EXP_DT IS '단말 보험 만료일자';
COMMENT ON COLUMN DEL_TS_CUST_INFO_H.CUST_TYP_CD IS '개인/법인 구분';

ALTER TABLE TS_CUST_INFO_TEMP ADD( EMAIL VARCHAR2 (100 BYTE) );
ALTER TABLE TS_CUST_INFO_TEMP ADD( EXP_DT VARCHAR2 (50 BYTE) );
ALTER TABLE TS_CUST_INFO_TEMP ADD( CUST_TYP_CD VARCHAR2 (10 BYTE) );

COMMENT ON COLUMN TS_CUST_INFO_TEMP.EMAIL IS '이메일';
COMMENT ON COLUMN TS_CUST_INFO_TEMP.EXP_DT IS '단말 보험 만료일자';
COMMENT ON COLUMN TS_CUST_INFO_TEMP.CUST_TYP_CD IS '개인/법인 구분';


ALTER TABLE TS_INSU_ACDNT RENAME COLUMN DEVL_MEMO TO DELV_MEMO;
COMMENT ON COLUMN TS_INSU_ACDNT.TYP_PRE_SEND IS '개통희망 여부 [1: 선개통, 2: 후개통]';

----------여기까지 등록 완료---------------

*******지불결제 URL 전달 I/F 테이블 가제: INA
CREATE TABLE IF_MTCS_PAY_URL(
	SEQ NUMBER NOT NULL,
	CLAIM_ID		VARCHAR2(50) NOT NULL,
	SVC_NUM	VARCHAR2(50) ,
	SVC_MGMT_NUM	VARCHAR2(50) ,
	EQP_INSU_SER_NUM	VARCHAR2(50) ,
	PAY_URL		VARCHAR2(200), 
	REG_DT DATE NOT NULL
);

CREATE SEQUENCE IF_MTCS_PAY_URL_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOORDER NOCYCLE;

CREATE INDEX IF_MTCS_PAY_URL_IX_CLAIM ON IF_MTCS_PAY_URL (CLAIM_ID, REG_DT );
CREATE INDEX IF_MTCS_PAY_URL_IX_SN ON IF_MTCS_PAY_URL (SVC_NUM, REG_DT );
CREATE INDEX IF_MTCS_PAY_URL_IX_SMN ON IF_MTCS_PAY_URL (SVC_MGMT_NUM, REG_DT );

COMMENT ON COLUMN IF_MTCS_PAY_URL.CLAIM_ID IS '사고접수번호';
COMMENT ON COLUMN IF_MTCS_PAY_URL.SVC_NUM IS '서비스번호(휴대폰번호)';
COMMENT ON COLUMN IF_MTCS_PAY_URL.SVC_MGMT_NUM IS '서비스관리번호';
COMMENT ON COLUMN IF_MTCS_PAY_URL.EQP_INSU_SER_NUM IS '단말기보험일련번호';
COMMENT ON COLUMN IF_MTCS_PAY_URL.PAY_URL IS '웹결제주소';
COMMENT ON COLUMN IF_MTCS_PAY_URL.REG_DT IS '등록일';

******* 택배 발송 완료 I/F 가제: IND
CREATE TABLE IF_MTCS_DELV_SEND(
	SEQ NUMBER NOT NULL,
	CLAIM_ID VARCHAR2(50) NOT NULL,
	SVC_MGMT_NUM VARCHAR2(50),
	COMP_TER_MDL VARCHAR2(50),
	COMP_MFACT_NM VARCHAR2(50),
	COMP_MOB_PRC VARCHAR2(50),
	JOIN_MOB_PRC VARCHAR2(50),
	PROC_DT VARCHAR2(50),
	DELV_ADDR VARCHAR2(500),	
	REG_DT DATE NOT NULL
);

CREATE SEQUENCE IF_MTCS_DELV_SEND_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOORDER NOCYCLE; 

CREATE INDEX IF_MTCS_DELV_SEND_IX_CLAIM ON IF_MTCS_DELV_SEND (CLAIM_ID, REG_DT);
CREATE INDEX IF_MTCS_DELV_SEND_IX_SMN ON IF_MTCS_DELV_SEND (SVC_MGMT_NUM, REG_DT );

COMMENT ON COLUMN IF_MTCS_DELV_SEND.CLAIM_ID IS '사고접수번호';
COMMENT ON COLUMN IF_MTCS_DELV_SEND.SVC_MGMT_NUM IS '서비스관리번호';
COMMENT ON COLUMN IF_MTCS_DELV_SEND.COMP_TER_MDL IS '보상단말기종';
COMMENT ON COLUMN IF_MTCS_DELV_SEND.COMP_MFACT_NM IS '보상단말제조사명';
COMMENT ON COLUMN IF_MTCS_DELV_SEND.COMP_MOB_PRC IS '보상단말기 출고가';
COMMENT ON COLUMN IF_MTCS_DELV_SEND.JOIN_MOB_PRC IS '가입단말기 출고가';
COMMENT ON COLUMN IF_MTCS_DELV_SEND.PROC_DT IS '택배발송일자';
COMMENT ON COLUMN IF_MTCS_DELV_SEND.DELV_ADDR IS '택배수신지 주소';
COMMENT ON COLUMN IF_MTCS_DELV_SEND.REG_DT IS '등록일';

******** 흥국 보상심사 승인
CREATE TABLE "TSPADM"."IF_HK_REWARD_IN" 
   (	"SVC_MGMT_NUM" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DY" VARCHAR2(8) NOT NULL ENABLE, 
	"CONTR_NO" VARCHAR2(20), 
	"ACDNT_DY" VARCHAR2(14), 
	"ACDNT_DET" VARCHAR2(1000), 
	"EQP_INSU_SER_NUM" NUMBER(10,0), 
	"CLAIM_ID" NUMBER NOT NULL ENABLE, 
	"MOB_PHN_NO" VARCHAR2(32), 				--큐브원 [PHONE]
	"MAKING_NO" VARCHAR2(20), 
	"PROD_FG" VARCHAR2(5), 
	"MODEL_NM" VARCHAR2(50), 
	"SVC_REG_DY" VARCHAR2(14), 
	"USE_YN" VARCHAR2(4), 
	"INSU_CO_CD" VARCHAR2(4), 
	"ACDNT_PLC" VARCHAR2(500), 
	"PRD_NM" VARCHAR2(100), 
	"PAY_BANK_CD" VARCHAR2(20), 
	"PAY_BANK_NM" VARCHAR2(100), 
	"PAY_BANK_ACC" VARCHAR2(50), 
	"ACCHOLDER_NM" VARCHAR2(500), 
	"ACCHOLDER_SSN" VARCHAR2(100), 
	"REPAIR_HST" VARCHAR2(2000), 
	"CUST_BIRTH" VARCHAR2(30),  				--큐브원 [JUMIN]
	"LOSS_DT" VARCHAR2(20), 
	"ENROLLED_PRICE" VARCHAR2(10), 
	"ACNT_TYPE" VARCHAR2(10), 
	"LOSS_COUNTRY" VARCHAR2(30), 
	"LOSS_LOCATION" VARCHAR2(200), 
	"CALLER_REL" VARCHAR2(30), 
	"CALLER_NAME" VARCHAR2(100),  			--큐브원 [NAME]
	"CUST_PHONE_NUM" VARCHAR2(30),  		--큐브원 [PHONE]
	"TRAVEL_INSU" VARCHAR2(10), 
	"AC_JUMIN_NUM" VARCHAR2(20),  		--큐브원 [JUMIN]
	"AC_NAME" VARCHAR2(100),  				--큐브원 [NAME]
	"BANK_NAME" VARCHAR2(50),
	"BANK_AC_NUM" VARCHAR2(50),  			--큐브원 [NAME]
	"AC_REL" VARCHAR2(20), 
	"IK_CONF" VARCHAR2(100),
	"CUST_NAME" VARCHAR2(100),	-- 큐브원 [NAME] -- 흥국 전용
	"ACNT_TIME" VARCHAR2(100),	 -- 흥국 전용
	"FST_SVC_DT" VARCHAR2(100),	 -- 흥국 전용
	"REG_DT" DATE, 
	"REGR" VARCHAR2(10), 
	"UPD_DT" DATE, 
	"UPDR" VARCHAR2(10), 
	"ETC1" VARCHAR2(2000), 
	 CONSTRAINT "IF_HK_REWARD_IN_PK" PRIMARY KEY ("SVC_MGMT_NUM", "CLAIM_ID"));
  

   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."SVC_MGMT_NUM" IS '서비스관리번호';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."REG_DY" IS '등록일자';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."CONTR_NO" IS '계약번호';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."ACDNT_DY" IS '사고일자';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."ACDNT_DET" IS '사고내용';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."EQP_INSU_SER_NUM" IS '단말보험일련번호';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."CLAIM_ID" IS '클래임ID';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."MOB_PHN_NO" IS '휴대폰번호';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."MAKING_NO" IS '제조번호';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."PROD_FG" IS '파손유형';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."MODEL_NM" IS '모델명';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."SVC_REG_DY" IS '서비스가입일자';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."USE_YN" IS '전송여부';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."INSU_CO_CD" IS '보험사코드';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."ACDNT_PLC" IS '사고장소';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."PRD_NM" IS '보험상품명';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."PAY_BANK_CD" IS '지급은행코드';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."PAY_BANK_NM" IS '지급은행명';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."PAY_BANK_ACC" IS '지급계좌번호';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."ACCHOLDER_NM" IS '예금주명';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."ACCHOLDER_SSN" IS '예금주 주민등록번호';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."REPAIR_HST" IS '부품수리내역';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."CUST_BIRTH" IS '가입자 생년월일';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."LOSS_DT" IS '사고일자 YYYYMMDDhhmm';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."ENROLLED_PRICE" IS '가입시 출고가';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."ACNT_TYPE" IS '사고형태 [분실, 도난, 완파, 화재, 파손, 침수]';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."LOSS_COUNTRY" IS '사고장소';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."LOSS_LOCATION" IS '사고지역';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."CALLER_REL" IS '명의자와 통화자 관계';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."CALLER_NAME" IS '통화자 이름';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."CUST_PHONE_NUM" IS '고객 연락처';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."TRAVEL_INSU" IS '여행자보험 가입여부';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."AC_JUMIN_NUM" IS '예금주 주민번호';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."AC_NAME" IS '예금주 이름';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."BANK_NAME" IS '입금 은행명';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."BANK_AC_NUM" IS '입금 계좌번호';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."AC_REL" IS '예금주와의 관계';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."IK_CONF" IS 'IK 보상 승인자';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."CUST_NAME" IS '고객명';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."ACNT_TIME" IS '사고시간';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."FST_SVC_DT" IS '개통일자';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."REG_DT" IS '등록일시';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."REGR" IS '등록자';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."UPD_DT" IS '수정일시';
   COMMENT ON COLUMN "TSPADM"."IF_HK_REWARD_IN"."UPDR" IS '수정자';


******** 한화 보상심사 승인
CREATE TABLE "TSPADM"."IF_HW_REWARD_IN" 
  (	"SVC_MGMT_NUM" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DY" VARCHAR2(8) NOT NULL ENABLE, 
	"CONTR_NO" VARCHAR2(20), 
	"ACDNT_DY" VARCHAR2(14), 
	"ACDNT_DET" VARCHAR2(1000), 
	"EQP_INSU_SER_NUM" NUMBER(10,0), 
	"CLAIM_ID" NUMBER NOT NULL ENABLE, 
	"MOB_PHN_NO" VARCHAR2(32), 				--큐브원 [PHONE]
	"MAKING_NO" VARCHAR2(20), 
	"PROD_FG" VARCHAR2(5), 
	"MODEL_NM" VARCHAR2(50), 
	"SVC_REG_DY" VARCHAR2(14), 
	"USE_YN" VARCHAR2(4), 
	"INSU_CO_CD" VARCHAR2(4), 
	"ACDNT_PLC" VARCHAR2(500), 
	"PRD_NM" VARCHAR2(100), 
	"PAY_BANK_CD" VARCHAR2(20), 
	"PAY_BANK_NM" VARCHAR2(100), 
	"PAY_BANK_ACC" VARCHAR2(50), 
	"ACCHOLDER_NM" VARCHAR2(500), 
	"ACCHOLDER_SSN" VARCHAR2(100), 
	"REPAIR_HST" VARCHAR2(2000), 
	"CUST_BIRTH" VARCHAR2(30),  				--큐브원 [JUMIN]
	"LOSS_DT" VARCHAR2(20), 
	"ENROLLED_PRICE" VARCHAR2(10), 
	"ACNT_TYPE" VARCHAR2(10), 
	"LOSS_COUNTRY" VARCHAR2(30), 
	"LOSS_LOCATION" VARCHAR2(200), 
	"CALLER_REL" VARCHAR2(30), 
	"CALLER_NAME" VARCHAR2(100),  			--큐브원 [NAME]
	"CUST_PHONE_NUM" VARCHAR2(30),  		--큐브원 [PHONE]
	"TRAVEL_INSU" VARCHAR2(10), 
	"AC_JUMIN_NUM" VARCHAR2(20),  		--큐브원 [JUMIN]
	"AC_NAME" VARCHAR2(100),  				--큐브원 [NAME]
	"BANK_NAME" VARCHAR2(50),
	"BANK_AC_NUM" VARCHAR2(50),  			--큐브원 [NAME]
	"AC_REL" VARCHAR2(20), 
	"IK_CONF" VARCHAR2(100),
	"REG_DT" DATE, 
	"REGR" VARCHAR2(10), 
	"UPD_DT" DATE, 
	"UPDR" VARCHAR2(10), 
	"ETC1" VARCHAR2(2000), 
	 CONSTRAINT "IF_HW_REWARD_IN_PK" PRIMARY KEY ("SVC_MGMT_NUM", "CLAIM_ID"));
  

   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."SVC_MGMT_NUM" IS '서비스관리번호';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."REG_DY" IS '등록일자';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."CONTR_NO" IS '계약번호';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."ACDNT_DY" IS '사고일자';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."ACDNT_DET" IS '사고내용';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."EQP_INSU_SER_NUM" IS '단말보험일련번호';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."CLAIM_ID" IS '클래임ID';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."MOB_PHN_NO" IS '휴대폰번호';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."MAKING_NO" IS '제조번호';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."PROD_FG" IS '파손유형';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."MODEL_NM" IS '모델명';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."SVC_REG_DY" IS '서비스가입일자';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."USE_YN" IS '전송여부';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."INSU_CO_CD" IS '보험사코드';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."ACDNT_PLC" IS '사고장소';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."PRD_NM" IS '보험상품명';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."PAY_BANK_CD" IS '지급은행코드';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."PAY_BANK_NM" IS '지급은행명';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."PAY_BANK_ACC" IS '지급계좌번호';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."ACCHOLDER_NM" IS '예금주명';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."ACCHOLDER_SSN" IS '예금주 주민등록번호';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."REPAIR_HST" IS '부품수리내역';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."CUST_BIRTH" IS '가입자 생년월일';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."LOSS_DT" IS '사고일자 YYYYMMDDhhmm';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."ENROLLED_PRICE" IS '가입시 출고가';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."ACNT_TYPE" IS '사고형태 [분실, 도난, 완파, 화재, 파손, 침수]';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."LOSS_COUNTRY" IS '사고장소';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."LOSS_LOCATION" IS '사고지역';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."CALLER_REL" IS '명의자와 통화자 관계';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."CALLER_NAME" IS '통화자 이름';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."CUST_PHONE_NUM" IS '고객 연락처';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."TRAVEL_INSU" IS '여행자보험 가입여부';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."AC_JUMIN_NUM" IS '예금주 주민번호';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."AC_NAME" IS '예금주 이름';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."BANK_NAME" IS '입금 은행명';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."BANK_AC_NUM" IS '입금 계좌번호';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."AC_REL" IS '예금주와의 관계';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."IK_CONF" IS 'IK 보상 승인자';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."REG_DT" IS '등록일시';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."REGR" IS '등록자';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."UPD_DT" IS '수정일시';
   COMMENT ON COLUMN "TSPADM"."IF_HW_REWARD_IN"."UPDR" IS '수정자';
   
   //--** 추가
   ALTER TABLE TS_INSU_ACDNT ADD( DELV_ADDR1 VARCHAR2 (400 BYTE) );
   ALTER TABLE TS_INSU_ACDNT ADD( DELV_ADDR2 VARCHAR2 (400 BYTE) );
   COMMENT ON COLUMN TS_INSU_ACDNT.DELV_ADDR1 IS '택배 수신 주소의 상세주소1';		
   COMMENT ON COLUMN TS_INSU_ACDNT.DELV_ADDR2 IS '택배 수신 주소의 상세주소2';		
   
   
	ALTER TABLE IF_ASTOSM ADD( AGREE_DT VARCHAR2 (20 BYTE) );
   	COMMENT ON COLUMN IF_ASTOSM.AGREE_DT IS '개인정보동의일시';
   	
	//-- 20180611 유통망 신규
	ALTER TABLE TS_INSU_ACDNT ADD( EMAIL VARCHAR2 (100 BYTE) );
	COMMENT ON COLUMN TS_INSU_ACDNT.EMAIL IS '이메일';
	
	ALTER TABLE PH_PROC_TGTR_LST ADD( EMAIL VARCHAR2 (100 BYTE) );
	ALTER TABLE PH_PROC_TGTR_LST ADD( SMS_YN VARCHAR2 (4 BYTE) );
	COMMENT ON COLUMN PH_PROC_TGTR_LST.EMAIL IS '이메일';
	COMMENT ON COLUMN PH_PROC_TGTR_LST.SMS_YN IS 'SMS 발송여부';
	ALTER TABLE PH_PROC_TGTR_HST ADD( EMAIL VARCHAR2 (100 BYTE) );
	ALTER TABLE PH_PROC_TGTR_HST ADD( SMS_YN VARCHAR2 (4 BYTE) );
	COMMENT ON COLUMN PH_PROC_TGTR_HST.EMAIL IS '이메일';
	COMMENT ON COLUMN PH_PROC_TGTR_HST.SMS_YN IS 'SMS 발송여부';
	ALTER TABLE PH_IF_PROC_TGTR_LST ADD( EMAIL VARCHAR2 (100 BYTE) );
	COMMENT ON COLUMN PH_IF_PROC_TGTR_LST.EMAIL IS '이메일';
	ALTER TABLE PH_IF_PROC_TGTR_LST_TMP ADD( EMAIL VARCHAR2 (100 BYTE) );
	COMMENT ON COLUMN PH_IF_PROC_TGTR_LST_TMP.EMAIL IS '이메일';


